### PR TITLE
Added an exemple to fireclickdetector

### PR DESCRIPTION
**Pull request by ViniDalvino**

### CODE REVIEW

**Comment by lingress** [comment]
The changes should be added to [docapi.lua](https://github.com/LoukaMB/SynapseX/blob/master/docapi.lua), not the HTML file itself. The version hosted on GitHub Pages is a built version of the documentation in the Lua scripts in the repository.

**Comment by ViniDalvino** [comment]
How can I put exemple to the the docapi.lua? Can you please show me a exemple?

**Comment by Eleazar9099** [comment]
SYNAPSE X it’s has been a month and haven’t received my code you guys are scamming lots of people if we don’t get our codes by 3 days I will tell the authorities about this(WARNING)

**Comment by lingress** [comment]
@Eleazar9099 
> SYNAPSE X it’s has been a month and haven’t received my code you guys are scamming lots of people if we don’t get our codes by 3 days I will tell the authorities about this(WARNING)

This comment contributes absolutely nothing to this PR and this repository. You should look elsewhere for whitelisting help as it's highly unlikely that you'll find it here.

**Comment by Eleazar9099** [comment]
Well where am I suppose to go they are scamming us with 20$ each person and we don’t get our codes like we payed for not even a email

**Comment by azamaniBoi** [comment]
i use to love synaspe x cuase i had full hope that they wouldn scam but hear we are getting scammed i feel sad and disapponited cuase i wasted my dad money to get this and i got scammed and beacuse f them i am crying everyday about how dumb i was to buy synaspe x know i have to buy protosmasher and yet people dont know how it feels being poor and asking for soemthing for 20 dollars and getting scamed cant wait to tell my dad about this :( 👎

**Comment by ESLRetr0** [comment]
If you think that you have been scammed, email [contact@synapse.to](mailto:contact@synapse.to). Commenting on a PR isn't going to get you very far.

**Comment by AZAMANI-sys** [comment]
Hi I know this is not related to this IN the PR but it says your account is terminated cause I have a account for synapse x and I was going to mega and I was going to download synapse x and it says you guys violated many term of services and I would like to ask how are we going to download synapse x cause I bought and I need it I have the account I just need to know how we going to download for people like us that bought and want to download it again on our devices.

**Comment by AZAMANI-sys** [comment]
I also contacted you guys

**Comment by ViniDalvino** [comment]
This is not the right place to contact for help with synapse. If you need help with getting your key go to x.synapse.to/missingkeyOn Feb. 17, 2020 13:32, AZAMANI-sys <notifications@github.com> wrote:I also contacted you guys

**Comment by WhatAreThose** [comment]
> Well where am I suppose to go they are scamming us with 20$ each person and we don’t get our codes like we payed for not even a email

Shut up, I got my key lol

**Comment by qwayqway1573** [comment]
I have got my key yet it's been 5 bays

**Comment by qwayqway1573** [comment]
It's been 6 bays and I have not got my key

**Comment by qwayqway1573** [comment]
> > Well where am I suppose to go they are scamming us with 20$ each person and we don’t get our codes like we payed for not even a email
> 
> 
> 
> Shut up, I got my key lol

You need

**Comment by qwayqway1573** [comment]
> > Well where am I suppose to go they are scamming us with 20$ each person and we don’t get our codes like we payed for not even a email
> 
> 
> 
> Shut up, I got my key lol 
You need to

**Pull request closed without merging**
